/* The following code was generated by JFlex 1.4.3 on 16/10/2020 13:37 */

package lang.parser;

import beaver.Symbol;
import beaver.Scanner;
import lang.ast.*;
import lang.ast.expr.*;
import lang.ast.cmd.*;
import lang.ast.types.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 16/10/2020 13:37 from the specification file
 * <tt>lang/parser/Lang.flex</tt>
 */
public class LangScanner extends Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int CHAR = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\63\1\2\1\0\1\4\1\1\22\0\1\4\1\27\1\62"+
    "\2\0\1\25\1\26\1\61\1\20\1\21\1\23\1\22\1\13\1\3"+
    "\1\10\1\24\12\7\1\12\1\11\1\30\1\32\1\31\2\0\1\6"+
    "\1\52\1\51\5\6\1\54\2\6\1\60\1\6\1\56\6\6\1\57"+
    "\1\55\4\6\1\16\1\64\1\17\3\0\1\43\1\65\1\5\1\44"+
    "\1\35\1\34\1\5\1\41\1\33\2\5\1\36\1\5\1\46\1\53"+
    "\1\45\1\5\1\42\1\37\1\47\1\50\1\5\1\40\3\5\1\14"+
    "\1\0\1\15\u05e2\0\12\7\206\0\12\7\306\0\12\7\u019c\0\12\7"+
    "\166\0\12\7\166\0\12\7\166\0\12\7\166\0\12\7\166\0\12\7"+
    "\166\0\12\7\166\0\12\7\166\0\12\7\166\0\12\7\140\0\12\7"+
    "\166\0\12\7\106\0\12\7\u0116\0\12\7\106\0\12\7\u0746\0\12\7"+
    "\46\0\12\7\u012c\0\12\7\200\0\12\7\246\0\12\7\6\0\12\7"+
    "\266\0\12\7\126\0\12\7\206\0\12\7\6\0\12\7\u89c6\0\12\7"+
    "\u02a6\0\12\7\46\0\12\7\306\0\12\7\26\0\12\7\126\0\12\7"+
    "\u0196\0\12\7\u5316\0\12\7\346\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\1\1\25\1\26"+
    "\1\27\11\4\5\5\1\30\1\31\1\32\1\33\1\2"+
    "\1\0\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\11\4\5\5\1\43\1\44\1\45\1\46\1\47\10\4"+
    "\1\50\1\4\2\5\1\51\2\5\2\4\1\52\1\4"+
    "\1\53\1\4\1\54\1\4\1\55\1\56\1\57\1\60"+
    "\1\61\1\4\1\62\1\63\1\4\1\64\1\4\1\65"+
    "\1\66";

  private static int [] zzUnpackAction() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\154\0\330\0\u010e\0\u0144"+
    "\0\u017a\0\154\0\154\0\u01b0\0\154\0\154\0\154\0\154"+
    "\0\154\0\154\0\154\0\154\0\154\0\154\0\154\0\u01e6"+
    "\0\u021c\0\u0252\0\u0288\0\u02be\0\u02f4\0\u032a\0\u0360\0\u0396"+
    "\0\u03cc\0\u0402\0\u0438\0\u046e\0\u04a4\0\u04da\0\u0510\0\u0546"+
    "\0\u057c\0\154\0\154\0\154\0\u05b2\0\u05e8\0\u061e\0\154"+
    "\0\154\0\154\0\154\0\154\0\154\0\u010e\0\u0654\0\u068a"+
    "\0\u06c0\0\u06f6\0\u072c\0\u0762\0\u0798\0\u07ce\0\u0804\0\u083a"+
    "\0\u0870\0\u08a6\0\u08dc\0\u0912\0\154\0\154\0\154\0\154"+
    "\0\u061e\0\u0948\0\u097e\0\u09b4\0\u09ea\0\u0a20\0\u0a56\0\u0a8c"+
    "\0\u0ac2\0\u010e\0\u0af8\0\u0b2e\0\u0b64\0\u0144\0\u0b9a\0\u0bd0"+
    "\0\u0c06\0\u0c3c\0\u010e\0\u0c72\0\u010e\0\u0ca8\0\u010e\0\u0cde"+
    "\0\u010e\0\u0144\0\u0144\0\u0144\0\u0144\0\u0d14\0\u010e\0\u010e"+
    "\0\u0d4a\0\u010e\0\u0d80\0\u010e\0\u010e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\5\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\3\1\33\1\34\1\35\1\36\2\7\1\37"+
    "\1\7\1\40\1\7\1\41\1\42\1\43\1\44\1\7"+
    "\1\45\1\46\1\7\1\47\1\50\1\51\2\10\1\52"+
    "\1\3\1\5\1\3\1\7\1\53\2\3\56\53\1\54"+
    "\2\3\1\55\1\53\70\0\1\5\66\0\1\56\67\0"+
    "\3\7\23\0\26\7\4\0\1\7\5\0\3\10\23\0"+
    "\26\10\4\0\1\10\7\0\1\11\1\57\67\0\1\60"+
    "\16\0\1\61\62\0\1\62\71\0\1\63\45\0\1\64"+
    "\105\0\1\65\40\0\3\7\23\0\1\7\1\66\12\7"+
    "\1\67\11\7\4\0\1\7\5\0\3\7\23\0\10\7"+
    "\1\70\15\7\4\0\1\7\5\0\3\7\23\0\3\7"+
    "\1\71\22\7\4\0\1\7\5\0\3\7\23\0\6\7"+
    "\1\72\17\7\4\0\1\7\5\0\3\7\23\0\2\7"+
    "\1\73\23\7\4\0\1\7\5\0\3\7\23\0\10\7"+
    "\1\74\15\7\4\0\1\7\5\0\3\7\23\0\7\7"+
    "\1\75\16\7\4\0\1\7\5\0\3\7\23\0\2\7"+
    "\1\76\23\7\4\0\1\7\5\0\3\7\23\0\7\7"+
    "\1\77\16\7\4\0\1\7\5\0\3\10\23\0\6\10"+
    "\1\100\17\10\4\0\1\10\5\0\3\10\23\0\20\10"+
    "\1\101\5\10\4\0\1\10\5\0\3\10\23\0\13\10"+
    "\1\102\12\10\4\0\1\10\5\0\3\10\23\0\20\10"+
    "\1\103\5\10\4\0\1\10\5\0\3\10\23\0\24\10"+
    "\1\104\1\10\4\0\1\10\42\0\1\105\3\0\1\106"+
    "\1\107\15\0\1\110\1\56\2\0\63\56\7\0\1\111"+
    "\63\0\3\7\23\0\2\7\1\112\23\7\4\0\1\7"+
    "\5\0\3\7\23\0\3\7\1\113\22\7\4\0\1\7"+
    "\5\0\3\7\23\0\4\7\1\114\21\7\4\0\1\7"+
    "\5\0\3\7\23\0\1\115\25\7\4\0\1\7\5\0"+
    "\3\7\23\0\10\7\1\116\3\7\1\117\11\7\4\0"+
    "\1\7\5\0\3\7\23\0\14\7\1\120\11\7\4\0"+
    "\1\7\5\0\3\7\23\0\1\121\25\7\4\0\1\7"+
    "\5\0\3\7\23\0\5\7\1\122\20\7\4\0\1\7"+
    "\5\0\3\7\23\0\15\7\1\123\10\7\4\0\1\7"+
    "\5\0\3\10\23\0\10\10\1\124\15\10\4\0\1\10"+
    "\5\0\3\10\23\0\20\10\1\125\5\10\4\0\1\10"+
    "\5\0\3\10\23\0\14\10\1\126\11\10\4\0\1\10"+
    "\5\0\3\10\23\0\1\127\25\10\4\0\1\10\5\0"+
    "\3\10\23\0\25\10\1\130\4\0\1\10\5\0\3\7"+
    "\23\0\7\7\1\131\16\7\4\0\1\7\5\0\3\7"+
    "\23\0\4\7\1\132\21\7\4\0\1\7\5\0\3\7"+
    "\23\0\2\7\1\133\23\7\4\0\1\7\5\0\3\7"+
    "\23\0\3\7\1\134\22\7\4\0\1\7\5\0\3\7"+
    "\23\0\11\7\1\135\14\7\4\0\1\7\5\0\3\7"+
    "\23\0\15\7\1\136\10\7\4\0\1\7\5\0\3\7"+
    "\23\0\10\7\1\137\15\7\4\0\1\7\5\0\3\7"+
    "\23\0\13\7\1\140\12\7\4\0\1\7\5\0\3\7"+
    "\23\0\2\7\1\141\23\7\4\0\1\7\5\0\3\10"+
    "\23\0\7\10\1\142\16\10\4\0\1\10\5\0\3\10"+
    "\23\0\3\10\1\143\22\10\4\0\1\10\5\0\3\10"+
    "\23\0\11\10\1\144\14\10\4\0\1\10\5\0\3\10"+
    "\23\0\25\10\1\145\4\0\1\10\5\0\3\7\23\0"+
    "\10\7\1\146\15\7\4\0\1\7\5\0\3\7\23\0"+
    "\2\7\1\147\23\7\4\0\1\7\5\0\3\7\23\0"+
    "\2\7\1\150\23\7\4\0\1\7\5\0\3\7\23\0"+
    "\7\7\1\151\16\7\4\0\1\7\5\0\3\7\23\0"+
    "\14\7\1\152\11\7\4\0\1\7\5\0\3\7\23\0"+
    "\14\7\1\153\11\7\4\0\1\7\5\0\3\7\23\0"+
    "\13\7\1\154\12\7\4\0\1\7\5\0\3\7\23\0"+
    "\2\7\1\155\23\7\4\0\1\7";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3510];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\4\1\2\11\1\1\13\11"+
    "\22\1\3\11\2\1\1\0\6\11\17\1\4\11\45\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
        private char c;  
        private int cCount = 0;
	private Symbol newToken(short id)
	{
		return new Symbol(id, yyline + 1, yycolumn + 1, yylength());
	}

	private Symbol newToken(short id, Object value)
	{
		return new Symbol(id, yyline + 1, yycolumn + 1, yylength(), value);
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LangScanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public LangScanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 290) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol nextToken() throws java.io.IOException, Scanner.Exception {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 53: 
          { return newToken(Terminals.RETURN, yytext());
          }
        case 55: break;
        case 10: 
          { return newToken(Terminals.COMMA, yytext());
          }
        case 56: break;
        case 28: 
          { return newToken(Terminals.TYBIND, yytext());
          }
        case 57: break;
        case 47: 
          { return newToken(Terminals.TYBOOL, yytext());
          }
        case 58: break;
        case 31: 
          { return newToken(Terminals.NEQ, yytext());
          }
        case 59: break;
        case 16: 
          { return newToken(Terminals.RPAREN, yytext());
          }
        case 60: break;
        case 17: 
          { return newToken(Terminals.PLUS, yytext());
          }
        case 61: break;
        case 2: 
          { /* Ignorar  */
          }
        case 62: break;
        case 29: 
          { return newToken(Terminals.RTR, yytext());
          }
        case 63: break;
        case 23: 
          { return newToken(Terminals.ATTR, yytext());
          }
        case 64: break;
        case 26: 
          { yybegin(YYINITIAL); return newToken(Terminals.CHAR, c);
          }
        case 65: break;
        case 49: 
          { return newToken(Terminals.NULL, yytext());
          }
        case 66: break;
        case 12: 
          { return newToken(Terminals.RBRACE, yytext());
          }
        case 67: break;
        case 13: 
          { return newToken(Terminals.LBRACKET, yytext());
          }
        case 68: break;
        case 42: 
          { return newToken(Terminals.ELSE, yytext());
          }
        case 69: break;
        case 3: 
          { return newToken(Terminals.SUB, yytext());
          }
        case 70: break;
        case 54: 
          { return newToken(Terminals.ITERATE, yytext());
          }
        case 71: break;
        case 48: 
          { return newToken(Terminals.TYVOID, yytext());
          }
        case 72: break;
        case 24: 
          { c = '\0'; yybegin(CHAR);
          }
        case 73: break;
        case 36: 
          { c = '\n';
          }
        case 74: break;
        case 1: 
          { throw new Scanner.Exception("carácter inesperado na entrada: '" + yytext() + "'");
          }
        case 75: break;
        case 7: 
          { return newToken(Terminals.DOT, yytext());
          }
        case 76: break;
        case 40: 
          { return newToken(Terminals.NEW, yytext() );
          }
        case 77: break;
        case 19: 
          { return newToken(Terminals.DIV, yytext());
          }
        case 78: break;
        case 27: 
          { c = '\\';
          }
        case 79: break;
        case 50: 
          { return newToken(Terminals.FALSE, yytext());
          }
        case 80: break;
        case 21: 
          { return newToken(Terminals.NOT, yytext());
          }
        case 81: break;
        case 15: 
          { return newToken(Terminals.LPAREN, yytext());
          }
        case 82: break;
        case 4: 
          { return newToken(Terminals.ID, yytext());
          }
        case 83: break;
        case 30: 
          { return newToken(Terminals.AND, yytext());
          }
        case 84: break;
        case 11: 
          { return newToken(Terminals.LBRACE, yytext());
          }
        case 85: break;
        case 41: 
          { return newToken(Terminals.TYINT, yytext());
          }
        case 86: break;
        case 14: 
          { return newToken(Terminals.RBRACKET, yytext());
          }
        case 87: break;
        case 37: 
          { c = '\t';
          }
        case 88: break;
        case 20: 
          { return newToken(Terminals.MOD, yytext());
          }
        case 89: break;
        case 43: 
          { return newToken(Terminals.READ, yytext());
          }
        case 90: break;
        case 5: 
          { return newToken(Terminals.TYID, yytext());
          }
        case 91: break;
        case 51: 
          { return newToken(Terminals.WHILE, yytext());
          }
        case 92: break;
        case 44: 
          { return newToken(Terminals.DATA,yytext());
          }
        case 93: break;
        case 38: 
          { c = '\b';
          }
        case 94: break;
        case 46: 
          { return newToken(Terminals.TYCHAR, yytext());
          }
        case 95: break;
        case 33: 
          { return newToken(Terminals.EQ, yytext());
          }
        case 96: break;
        case 52: 
          { return newToken(Terminals.PRINT, yytext());
          }
        case 97: break;
        case 25: 
          { c = yytext().charAt(0);
          }
        case 98: break;
        case 45: 
          { return newToken(Terminals.TRUE, yytext());
          }
        case 99: break;
        case 39: 
          { return newToken(Terminals.FLOAT, new Float(yytext()) );
          }
        case 100: break;
        case 35: 
          { c = '\r';
          }
        case 101: break;
        case 18: 
          { return newToken(Terminals.MULT, yytext());
          }
        case 102: break;
        case 6: 
          { return newToken(Terminals.INT, new Integer(yytext()));
          }
        case 103: break;
        case 8: 
          { return newToken(Terminals.SEMI, yytext());
          }
        case 104: break;
        case 22: 
          { return newToken(Terminals.LT, yytext());
          }
        case 105: break;
        case 34: 
          { return newToken(Terminals.IF, yytext());
          }
        case 106: break;
        case 9: 
          { return newToken(Terminals.COLON, yytext());
          }
        case 107: break;
        case 32: 
          { return newToken(Terminals.RTL, yytext());
          }
        case 108: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {          return newToken(Terminals.EOF, "end-of-file");
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
